// 模拟金库数据
export const mockVaults = [
  {
    id: "1",
    name: "USD Coin",
    symbol: "USDC",
    platform: "Euler Base",
    icon: "/usdc.svg",
    price: "1.00",
    priceSource: "ChainlinkOracle",
    supplyApy: 7.28,
    borrowApy: 5.96,
    totalSupply: 13.21,
    totalSupplyNative: "13.21M USDC",
    totalBorrow: 11.81,
    totalBorrowNative: "11.81M USDC",
    utilization: 89.41,
    exposure: 7,
  },
  {
    id: "2",
    name: "USD Stablecoin",
    symbol: "USDS",
    platform: "Euler Base",
    icon: "/usds.svg",
    price: "1.00",
    priceSource: "ChainlinkOracle",
    supplyApy: 10.11,
    borrowApy: 8.45,
    totalSupply: 12.25,
    totalSupplyNative: "12.25M USDS",
    totalBorrow: 10.86,
    totalBorrowNative: "10.86M USDS",
    utilization: 88.69,
    exposure: 7,
  },
  {
    id: "3",
    name: "Wrapped Ethereum",
    symbol: "WETH",
    platform: "Euler Base",
    icon: "/weth.svg",
    price: "2,019.00",
    priceSource: "ChainlinkOracle",
    supplyApy: 3.96,
    borrowApy: 2.85,
    totalSupply: 5.14,
    totalSupplyNative: "2.56K WETH",
    totalBorrow: 4.06,
    totalBorrowNative: "2.01K WETH",
    utilization: 79.07,
    exposure: 6,
  },
  {
    id: "4",
    name: "Wrapped Ethereum Staked",
    symbol: "weETH",
    platform: "Euler Base",
    icon: "/weeth.svg",
    price: "2,138.00",
    priceSource: "ChainlinkOracle",
    supplyApy: 0.0,
    borrowApy: 0.0,
    totalSupply: 4.19,
    totalSupplyNative: "1.96K weETH",
    totalBorrow: 0.02,
    totalBorrowNative: "10.57 weETH",
    utilization: 0.54,
    exposure: 6,
  },
  {
    id: "5",
    name: "Euro Coin",
    symbol: "EURC",
    platform: "Euler Base",
    icon: "/eurc.svg",
    price: "1.09",
    priceSource: "ChainlinkOracle",
    supplyApy: 1.25,
    borrowApy: 0.95,
    totalSupply: 3.47,
    totalSupplyNative: "3.21M EURC",
    totalBorrow: 1.21,
    totalBorrowNative: "1.12M EURC",
    utilization: 34.99,
    exposure: 7,
  },
  {
    id: "6",
    name: "Coinbase Wrapped Bitcoin",
    symbol: "CBBTC",
    platform: "Euler Base",
    icon: "/cbbtc.svg",
    price: "84,650.00",
    priceSource: "ChainlinkOracle",
    supplyApy: 2.65,
    borrowApy: 1.85,
    totalSupply: 2.8,
    totalSupplyNative: "33.09 CBBTC",
    totalBorrow: 0.4,
    totalBorrowNative: "4.69 CBBTC",
    utilization: 14.17,
    exposure: 6,
  },
  {
    id: "7",
    name: "USD Reserve",
    symbol: "USR",
    platform: "Apostro Resolv",
    icon: "/usr.svg",
    price: "1.00",
    priceSource: "ChainlinkOracle",
    supplyApy: 5.86,
    borrowApy: 4.25,
    totalSupply: 2.39,
    totalSupplyNative: "2.39M USR",
    totalBorrow: 1.23,
    totalBorrowNative: "1.23M USR",
    utilization: 51.36,
    exposure: 3,
  },
  {
    id: "8",
    name: "Principal Token USR",
    symbol: "PT-USR-24APR2025",
    platform: "Apostro Resolv",
    icon: "/pt-usr.svg",
    price: "0.99",
    priceSource: "ChainlinkOracle",
    supplyApy: 0.0,
    borrowApy: 0.0,
    totalSupply: 2.15,
    totalSupplyNative: "2.17M PT-USR-24...",
    totalBorrow: 0.0,
    totalBorrowNative: "0 PT-USR-24...",
    utilization: 0.0,
    exposure: 0,
  },
  {
    id: "9",
    name: "USD Coin",
    symbol: "USDC",
    platform: "Apostro Resolv",
    icon: "/usdc.svg",
    price: "1.00",
    priceSource: "ChainlinkOracle",
    supplyApy: 8.51,
    borrowApy: 6.75,
    totalSupply: 1.59,
    totalSupplyNative: "1.59M USDC",
    totalBorrow: 1.02,
    totalBorrowNative: "1.02M USDC",
    utilization: 64.23,
    exposure: 2,
  },
]

// 模拟抵押品数据
export const mockCollaterals = [
  {
    id: "1",
    name: "Wrapped Ethereum",
    symbol: "WETH",
    platform: "Euler Base",
    icon: "/weth.svg",
    maxLtv: 85.0,
    ltv: 87.0,
    adapterPrice: 2019,
    oracleProvider: "Chainlink",
    vaultAddress: "0x8591...b410",
  },
  {
    id: "2",
    name: "Wrapped Staked Ethereum",
    symbol: "wstETH",
    platform: "Euler Base",
    icon: "/wsteth.svg",
    maxLtv: 81.0,
    ltv: 83.0,
    adapterPrice: 2408,
    oracleProvider: "Chainlink",
    vaultAddress: "0x7b18...2609",
  },
  {
    id: "3",
    name: "Coinbase Ethereum",
    symbol: "cbETH",
    platform: "Euler Base",
    icon: "/cbeth.svg",
    maxLtv: 78.0,
    ltv: 80.0,
    adapterPrice: 2204,
    oracleProvider: "Chainlink",
    vaultAddress: "0x358f...ea49",
  },
  {
    id: "4",
    name: "Wrapped Ethereum",
    symbol: "weETH",
    platform: "Euler Base",
    icon: "/weeth.svg",
    maxLtv: 78.0,
    ltv: 80.0,
    adapterPrice: 2138,
    oracleProvider: "Chainlink",
    vaultAddress: "0xd4A8...0d14",
  },
  {
    id: "5",
    name: "Euro Coin",
    symbol: "EURC",
    platform: "Euler Base",
    icon: "/eurc.svg",
    maxLtv: 88.0,
    ltv: 90.0,
    adapterPrice: 1.091211,
    oracleProvider: "Chainlink",
    vaultAddress: "0x9ECD...7117",
  },
]

// 模拟交易响应
export const mockTransactionResponse = {
  success: true,
  message: "交易已提交",
  txHash: "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef",
}

// 添加模拟仓位数据
export const mockPositions = [
  {
    id: "1",
    totalDebt: "1000",
    debtToken: "0xUSDC",
    debtTokenSymbol: "USDC",
    debtTokenIcon: "/usdc.svg",
    collateralAmount: "1.5",
    collateralToken: "0xWETH",
    collateralTokenSymbol: "WETH",
    collateralTokenIcon: "/weth.svg",
    ltv: 0.65,
    apy: 0.045,
    exchangeRate: 1.02
  }
]

